GET http://localhost:3000/product

###
GET http://localhost:3000/product/656a194352e6d0f2e1864110


###
POST https://digi-express-homepage-api.onrender.com/product
Content-Type: application/json

{
    "category": "laptop",
        "name": "Legion 7",
        "brand": "Lenovo",
        "model": "Legion 7i",
        "price": 1799.99,
        "specifications": [
            "15.6-inch 240Hz display",
            "Intel Core i9",
            "32GB RAM",
            "1TB NVMe SSD"
        ],
        "image": "lenovo_legion_7.jpg",
        "description": "High-performance gaming laptop with advanced features.",
        "warranty": {
            "duration": 2,
            "description": "Premium Care warranty available."
        }
}