GET http://localhost:3000/product

###
GET http://localhost:3000/product/656a194352e6d0f2e1864110


###
POST http://localhost:3000/product
Content-Type: application/json

{
    "name": "Example Laptop",
    "brand": "TechCo",
    "model": "SuperBook Pro",
    "price": 102999,
    "specifications": ["15-inch display", "8GB RAM", "256GB SSD"],
    "image": "http://example.com/images/laptop.jpg",
    "description": "A powerful and sleek laptop for your computing needs.",
    "warranty": {
        "duration": 2,
        "description": "Limited warranty covering manufacturing defects."
    }
}