GET http://localhost:3000/product

###
GET http://localhost:3000/product/656a194352e6d0f2e1864110


###
POST https://digi-express-homepage-api.onrender.com/product
Content-Type: application/json

{
        "category": "laptop",
        "name": "MacBook Pro",
        "brand": "Apple",
        "model": "MacBook Pro 16-inch",
        "price": 2399.99,
        "specifications": [
            "16-inch Retina display",
            "Intel Core i9",
            "32GB RAM",
            "1TB SSD"
        ],
        "image": "macbook_pro_16.jpg",
        "description": "High-performance laptop for creative professionals.",
        "warranty": {
            "duration": 1,
            "description": "AppleCare protection plan available."
        }
    }